# CI workflow for shell scripts
name: ci-push-script

on:
  push:
    branches:
      - "main"
      - "master"
      - "hotfix/**"
      - "release/**"
      - "develop"
      - "feature/**"
    paths:
      - "**/*.sh"
      - ".github/workflows/ci-push-script.yaml"
      - ".github/workflows/reusable-ci-script.yaml"
  pull_request:
    branches:
      - "main"
      - "master"
      - "hotfix/**"
      - "release/**"
      - "develop"
      - "feature/**"
    paths:
      - "**/*.sh"
      - ".github/workflows/ci-push-script.yaml"
      - ".github/workflows/reusable-ci-script.yaml"

jobs:
  script-ci:
    uses: ./.github/workflows/reusable-ci-script.yaml
    with:
      script_path: "**/*.sh"
    permissions:
      checks: write
      contents: read
      pull-requests: write
